CREATE TABLE IF NOT EXISTS hits (
    id bigint generated by default as identity PRIMARY KEY,
    app varchar(50) NOT NULL,
    uri varchar(50) NOT NULL,
    ip varchar(20) NOT NULL,
    hit_timestamp timestamp NOT NULL
    );